# Generated by Django 2.2.7 on 2019-12-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191204_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='usi',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
